apiVersion: v1
kind: Pod
metadata:
  name: giropops-pod
spec:
  containers:
    - name: giropops-container
      image: nginx:latest
      ports:
        - containerPort: 80
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: giropops-test
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: giropops-test
              key: password
  restartPolicy: Always