apiVersion: v1
kind: Pod
metadata:
  name: private-image-pod
spec:
  containers:
  - name: private-image-container
    image: my-private-registry/my-private-image:latest
  imagePullSecrets:
  - name: dockerhub-test