apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: nginx-prometheus-rules
  namespace: monitoring
  labels:
    prometheus: k8s
    app.kubernetes.io/name: kube-prometheus
    app.kubernetes.io/part-of: kube-prometheus
spec:
  groups:
  - name: nginx-prometheus-rule
    rules:
    - alert: NginxDown
      expr: up{job="nginx-exporter"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Nginx is down"
        description: "Nginx fora do ar"
    - alert: NginxHighRequestLatency
      expr: rate(nginx_http_request_duration_seconds_sum{job="nginx-exporter"}[5m]) / rate(nginx_http_request_duration_seconds_count{job="nginx-exporter"}[5m]) > 0.5
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "High request latency on Nginx"
        description: "Nginx has high request latency for more than 1 minute"
    - alert: NginxHighRequestRate
      expr: rate(nginx_http_requests_total{job="nginx-exporter"}[5m]) > 100
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "High request rate on Nginx"
        description: "Nginx has high request rate for more than 1 minute"