apiVersion: v1
data:
  nginx.conf: |-
    events {}

    http {
        server {
            listen 80;
            listen 443 ssl;

            ssl_certificate /etc/nginx/tls/certificado.crt;
            ssl_certificate_key /etc/nginx/tls/chave-privada.key;

            location / {
                return 200 'Hello, SANGUE BOM!';
                add_header Content-Type text/plain;
            }
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-config
