deployments:
  giropopsSenhas:
    name: giropops-senhas
    image: linuxtips/giropops-senhas:1.0
    replicas: 3
    ports: 
      - port: 5000
        targetPort: 5000
        name: giropops-senhas-port
        serviceType: NodePort
        nodePort: 32700
      - port: 8088
        targetPort: 8088
        name: giropops-senhas-metrics
        serviceType: ClusterIP
    labels:
      app: giropops-senhas
      env: labs
      live: "true"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  redis:
    name: redis-helm
    image: redis:latest
    replicas: 1
    port: 6379
    labels:
      app: redis
      env: labs
      live: "true"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
services:
  giropopsSenhas:
    ports: 
    - port: 5000
      targetPort: 5000
      name: giropops-senhas-port
      serviceType: NodePort
      nodePort: 32700
    - port: 8088
      targetPort: 8088
      name: giropops-senhas-metrics
      serviceType: ClusterIP
    labels:
      app: giropops-senhas
      env: labs
      live: "true"
  redis:
    ports: 
      - port: 6379
        targetPort: 6379
        name: redis-port
        serviceType: ClusterIP
    labels:
      app: redis
      env: labs
      live: "true"