apiVersion: v1
kind: Pod
metadata:
  name: giropops-pod
  labels:
    name: myapp
spec:
  containers:
  - name: giropops-container
    image: nginx
    env:
      - name: USERNME
        valueFrom:
          secretKeyRef:
            name: primeiro-secret
            key: username
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: primeiro-secret
            key: password
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
