apiVersion: apps/v1
kind: Deployment
metadata:
  name: giropops-senhas
  labels:
    app: giropops-senhas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: giropops-senhas
  template:
    metadata:
      labels:
        app: giropops-senhas
    spec:
      containers:
        - name: giropops-senhas
          image: linuxtips/giropops-senhas:1.0
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: redis-service
          ports:
            - containerPort: 5000
