apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform
rules:
- apiGroups: ["", "apps"] # "" indicates the core API group
  resources: ["deployments", "pods"]
  verbs: ["get", "list", "create"]