apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    env: dev
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      name: http